/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemingRouteImport } from './routes/theming'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as DemoLoadingRouteImport } from './routes/demo.loading'
import { Route as ComponentsSlugRouteImport } from './routes/components.$slug'

const ThemingRoute = ThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLoadingRoute = DemoLoadingRouteImport.update({
  id: '/demo/loading',
  path: '/demo/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theming': typeof ThemingRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/demo/loading': typeof DemoLoadingRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theming': typeof ThemingRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/demo/loading': typeof DemoLoadingRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/theming': typeof ThemingRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/demo/loading': typeof DemoLoadingRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/theming' | '/components/$slug' | '/demo/loading' | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/theming' | '/components/$slug' | '/demo/loading' | '/components'
  id:
    | '__root__'
    | '/'
    | '/theming'
    | '/components/$slug'
    | '/demo/loading'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ThemingRoute: typeof ThemingRoute
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  DemoLoadingRoute: typeof DemoLoadingRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theming': {
      id: '/theming'
      path: '/theming'
      fullPath: '/theming'
      preLoaderRoute: typeof ThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/loading': {
      id: '/demo/loading'
      path: '/demo/loading'
      fullPath: '/demo/loading'
      preLoaderRoute: typeof DemoLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ThemingRoute: ThemingRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
  DemoLoadingRoute: DemoLoadingRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
